# 自动清理陈旧的PR和Issue
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '25 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        days-before-stale: 31
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: '【action自动生成】问题不活跃，即将关闭'
        stale-pr-message: '【action自动生成】PR不活跃，即将关闭'
        stale-issue-label: '不活跃'
        stale-pr-label: '不活跃'
        close-issue-message: '【action自动生成】问题过于陈旧，已经关闭'
        close-pr-message: '【action自动生成】PR过于陈旧，已经关闭'
        close-issue-label: '因不活跃关闭'
        close-pr-label: '因不活跃关闭'
